"""Tests for v0.9.1 WirePlumber rule install state integrity and recovery."""
from __future__ import annotations

import json
from pathlib import Path

import pipetune
from pipetune import cli
from pipetune.wireplumber.install import run_install_rule
from pipetune.wireplumber.integrity import (
    run_cleanup_rolled_back,
    run_repair_rule_state,
    run_state_doctor,
    run_verify_rule,
)
from pipetune.wireplumber.manifest import load_manifest, save_manifest, RuleManifestEntry
from pipetune.wireplumber.rollback import run_rollback_rule

_VALID_PREVIEW_CONTENT = """\
-- PREVIEW ONLY — NOT INSTALLED
-- Generated by PipeTune Linux
rule = {
  matches = {},
  apply_properties = {},
}
"""

_ALT_PREVIEW_CONTENT = """\
-- PREVIEW ONLY — NOT INSTALLED
-- Alternate rule for duplicate testing
rule = {
  matches = {"different"},
  apply_properties = {},
}
"""


def _make_preview(tmp_path: Path, name: str = "test-rule.lua", content: str = _VALID_PREVIEW_CONTENT) -> Path:
    p = tmp_path / "previews" / "wireplumber" / name
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")
    return p


def _isolated(tmp_path: Path) -> tuple[Path, Path]:
    rule_dir = tmp_path / "config" / "wireplumber" / "wireplumber.conf.d"
    manifest_path = tmp_path / "state" / "wireplumber-rules" / "manifests.json"
    return rule_dir, manifest_path


def _install(tmp_path: Path, preview: Path, rule_dir: Path, manifest_path: Path):
    return run_install_rule(
        str(preview), user_only=True, dry_run=False, confirm_install=True,
        rule_dir=rule_dir, manifest_path=manifest_path,
    )


# ---------------------------------------------------------------------------
# Version check
# ---------------------------------------------------------------------------

def test_version_is_091() -> None:
    assert pipetune.__version__ == "0.9.1"


# ---------------------------------------------------------------------------
# state-doctor: clean pass
# ---------------------------------------------------------------------------

def test_state_doctor_clean_pass(tmp_path: Path) -> None:
    rule_dir, manifest_path = _isolated(tmp_path)
    preview = _make_preview(tmp_path)
    _install(tmp_path, preview, rule_dir, manifest_path)

    report = run_state_doctor(manifest_path=manifest_path, rule_dir=rule_dir)

    assert report.verdict == "pass"
    assert report.active_count == 1
    assert report.missing_file_count == 0
    assert report.orphan_file_count == 0
    assert report.checksum_mismatch_count == 0


def test_state_doctor_empty_manifest_pass(tmp_path: Path) -> None:
    _, manifest_path = _isolated(tmp_path)
    rule_dir = tmp_path / "wr"

    report = run_state_doctor(manifest_path=manifest_path, rule_dir=rule_dir)

    assert report.verdict in ("pass", "warn")
    assert report.active_count == 0


# ---------------------------------------------------------------------------
# state-doctor: missing installed file
# ---------------------------------------------------------------------------

def test_state_doctor_detects_missing_installed_file(tmp_path: Path) -> None:
    rule_dir, manifest_path = _isolated(tmp_path)
    preview = _make_preview(tmp_path)
    install_report = _install(tmp_path, preview, rule_dir, manifest_path)

    for f in rule_dir.glob("*.lua"):
        f.unlink()

    report = run_state_doctor(manifest_path=manifest_path, rule_dir=rule_dir)

    assert report.missing_file_count == 1
    assert report.verdict == "warn"
    assert any("missing installed file" in w for w in report.warnings)


# ---------------------------------------------------------------------------
# state-doctor: orphan file detection
# ---------------------------------------------------------------------------

def test_state_doctor_detects_orphan_pipetune_file(tmp_path: Path) -> None:
    rule_dir, manifest_path = _isolated(tmp_path)
    rule_dir.mkdir(parents=True, exist_ok=True)
    orphan = rule_dir / "90-pipetune-deadbeef.lua"
    orphan.write_text("-- orphan\n", encoding="utf-8")

    report = run_state_doctor(manifest_path=manifest_path, rule_dir=rule_dir)

    assert report.orphan_file_count == 1
    assert str(orphan) in report.orphan_files
    assert report.verdict == "warn"


# ---------------------------------------------------------------------------
# state-doctor: checksum mismatch
# ---------------------------------------------------------------------------

def test_state_doctor_detects_checksum_mismatch(tmp_path: Path) -> None:
    rule_dir, manifest_path = _isolated(tmp_path)
    preview = _make_preview(tmp_path)
    _install(tmp_path, preview, rule_dir, manifest_path)

    installed_files = list(rule_dir.glob("*.lua"))
    installed_files[0].write_text("-- tampered content\n", encoding="utf-8")

    report = run_state_doctor(manifest_path=manifest_path, rule_dir=rule_dir)

    assert report.checksum_mismatch_count == 1
    assert report.verdict == "warn"


# ---------------------------------------------------------------------------
# state-doctor: JSON output
# ---------------------------------------------------------------------------

def test_state_doctor_json_parses(tmp_path: Path) -> None:
    from pipetune.wireplumber.integrity import render_state_doctor_json

    _, manifest_path = _isolated(tmp_path)
    rule_dir = tmp_path / "wr"
    report = run_state_doctor(manifest_path=manifest_path, rule_dir=rule_dir)
    data = json.loads(render_state_doctor_json(report))

    assert data["safety"]["read_only"] is True
    assert "active_count" in data
    assert "orphan_file_count" in data


# ---------------------------------------------------------------------------
# duplicate install protection
# ---------------------------------------------------------------------------

def test_duplicate_install_refused(tmp_path: Path) -> None:
    rule_dir, manifest_path = _isolated(tmp_path)
    preview = _make_preview(tmp_path)
    _install(tmp_path, preview, rule_dir, manifest_path)

    report = run_install_rule(
        str(preview), user_only=True, dry_run=False, confirm_install=True,
        rule_dir=rule_dir, manifest_path=manifest_path,
    )

    assert report.passed is False
    assert any("Duplicate install refused" in e for e in report.errors)


def test_different_content_allows_second_install(tmp_path: Path) -> None:
    rule_dir, manifest_path = _isolated(tmp_path)
    preview1 = _make_preview(tmp_path, "rule1.lua", _VALID_PREVIEW_CONTENT)
    preview2 = _make_preview(tmp_path, "rule2.lua", _ALT_PREVIEW_CONTENT)
    _install(tmp_path, preview1, rule_dir, manifest_path)

    report = run_install_rule(
        str(preview2), user_only=True, dry_run=False, confirm_install=True,
        rule_dir=rule_dir, manifest_path=manifest_path,
    )

    assert report.passed is True
    assert load_manifest(manifest_path).__len__() == 2


# ---------------------------------------------------------------------------
# verify-rule
# ---------------------------------------------------------------------------

def test_verify_rule_valid_install(tmp_path: Path) -> None:
    rule_dir, manifest_path = _isolated(tmp_path)
    preview = _make_preview(tmp_path)
    install_report = _install(tmp_path, preview, rule_dir, manifest_path)

    report = run_verify_rule(install_report.install_id, manifest_path=manifest_path)

    assert report.verdict == "pass"
    assert report.passed is True
    assert report.file_exists is True
    assert report.checksum_state == "valid"


def test_verify_rule_unknown_id(tmp_path: Path) -> None:
    _, manifest_path = _isolated(tmp_path)

    report = run_verify_rule("unknown0", manifest_path=manifest_path)

    assert report.passed is False
    assert any("Unknown install_id" in e for e in report.errors)


def test_verify_rule_detects_missing_file(tmp_path: Path) -> None:
    rule_dir, manifest_path = _isolated(tmp_path)
    preview = _make_preview(tmp_path)
    install_report = _install(tmp_path, preview, rule_dir, manifest_path)
    for f in rule_dir.glob("*.lua"):
        f.unlink()

    report = run_verify_rule(install_report.install_id, manifest_path=manifest_path)

    assert report.passed is False
    assert any("missing" in e.lower() for e in report.errors)


def test_verify_rule_detects_checksum_mismatch(tmp_path: Path) -> None:
    rule_dir, manifest_path = _isolated(tmp_path)
    preview = _make_preview(tmp_path)
    install_report = _install(tmp_path, preview, rule_dir, manifest_path)
    for f in rule_dir.glob("*.lua"):
        f.write_text("-- tampered\n", encoding="utf-8")

    report = run_verify_rule(install_report.install_id, manifest_path=manifest_path)

    assert "checksum_mismatch" in report.checksum_state
    assert any("mismatch" in w.lower() for w in report.warnings)


def test_verify_rule_json_parses(tmp_path: Path) -> None:
    from pipetune.wireplumber.integrity import render_verify_rule_json

    _, manifest_path = _isolated(tmp_path)
    report = run_verify_rule("unknown0", manifest_path=manifest_path)
    data = json.loads(render_verify_rule_json(report))

    assert data["safety"]["read_only"] is True
    assert "checksum_state" in data


# ---------------------------------------------------------------------------
# repair-rule-state: dry-run only, no modifications
# ---------------------------------------------------------------------------

def test_repair_rule_state_dry_run_changes_nothing(tmp_path: Path) -> None:
    rule_dir, manifest_path = _isolated(tmp_path)
    preview = _make_preview(tmp_path)
    _install(tmp_path, preview, rule_dir, manifest_path)

    entries_before = load_manifest(manifest_path)
    run_repair_rule_state(manifest_path=manifest_path, rule_dir=rule_dir)
    entries_after = load_manifest(manifest_path)

    assert [e.install_id for e in entries_before] == [e.install_id for e in entries_after]


def test_repair_rule_state_proposes_action_for_missing_file(tmp_path: Path) -> None:
    rule_dir, manifest_path = _isolated(tmp_path)
    preview = _make_preview(tmp_path)
    _install(tmp_path, preview, rule_dir, manifest_path)
    for f in rule_dir.glob("*.lua"):
        f.unlink()

    report = run_repair_rule_state(manifest_path=manifest_path, rule_dir=rule_dir)

    assert any("Mark entry" in a for a in report.proposed_actions)


def test_repair_rule_state_json_parses(tmp_path: Path) -> None:
    from pipetune.wireplumber.integrity import render_repair_report_json

    _, manifest_path = _isolated(tmp_path)
    rule_dir = tmp_path / "wr"
    report = run_repair_rule_state(manifest_path=manifest_path, rule_dir=rule_dir)
    data = json.loads(render_repair_report_json(report))

    assert data["dry_run"] is True
    assert data["safety"]["read_only"] is True


# ---------------------------------------------------------------------------
# cleanup-rolled-back-rules
# ---------------------------------------------------------------------------

def test_cleanup_dry_run_changes_nothing(tmp_path: Path) -> None:
    rule_dir, manifest_path = _isolated(tmp_path)
    preview = _make_preview(tmp_path)
    install_report = _install(tmp_path, preview, rule_dir, manifest_path)
    run_rollback_rule(install_report.install_id, dry_run=False, confirm_rollback=True, manifest_path=manifest_path)

    entries_before = load_manifest(manifest_path)
    run_cleanup_rolled_back(dry_run=True, confirm_cleanup=False, manifest_path=manifest_path)
    entries_after = load_manifest(manifest_path)

    assert len(entries_before) == len(entries_after)


def test_cleanup_confirm_removes_only_safe_rolled_back_entries(tmp_path: Path) -> None:
    rule_dir, manifest_path = _isolated(tmp_path)
    preview1 = _make_preview(tmp_path, "rule1.lua", _VALID_PREVIEW_CONTENT)
    preview2 = _make_preview(tmp_path, "rule2.lua", _ALT_PREVIEW_CONTENT)
    r1 = _install(tmp_path, preview1, rule_dir, manifest_path)
    r2 = _install(tmp_path, preview2, rule_dir, manifest_path)

    run_rollback_rule(r1.install_id, dry_run=False, confirm_rollback=True, manifest_path=manifest_path)

    report = run_cleanup_rolled_back(dry_run=False, confirm_cleanup=True, manifest_path=manifest_path)

    assert report.passed is True
    assert report.removed_count == 1
    entries = load_manifest(manifest_path)
    assert all(e.install_id != r1.install_id for e in entries)
    assert any(e.install_id == r2.install_id for e in entries)


def test_cleanup_refuses_both_flags(tmp_path: Path) -> None:
    _, manifest_path = _isolated(tmp_path)

    report = run_cleanup_rolled_back(dry_run=True, confirm_cleanup=True, manifest_path=manifest_path)

    assert report.passed is False
    assert any("Cannot pass both" in e for e in report.errors)


def test_cleanup_json_parses(tmp_path: Path) -> None:
    from pipetune.wireplumber.integrity import render_cleanup_report_json

    _, manifest_path = _isolated(tmp_path)
    report = run_cleanup_rolled_back(dry_run=True, confirm_cleanup=False, manifest_path=manifest_path)
    data = json.loads(render_cleanup_report_json(report))

    assert data["dry_run"] is True
    assert "removed_count" in data


# ---------------------------------------------------------------------------
# rollback checksum mismatch protection
# ---------------------------------------------------------------------------

def test_rollback_refuses_checksum_mismatch(tmp_path: Path) -> None:
    rule_dir, manifest_path = _isolated(tmp_path)
    preview = _make_preview(tmp_path)
    install_report = _install(tmp_path, preview, rule_dir, manifest_path)

    for f in rule_dir.glob("*.lua"):
        f.write_text("-- tampered content\n", encoding="utf-8")

    report = run_rollback_rule(
        install_report.install_id, dry_run=False, confirm_rollback=True, manifest_path=manifest_path
    )

    assert report.passed is False
    assert any("mismatch" in e.lower() for e in report.errors)


# ---------------------------------------------------------------------------
# CLI integration
# ---------------------------------------------------------------------------

def test_cli_state_doctor_exits_zero(tmp_path: Path, monkeypatch, capsys) -> None:
    from pipetune.wireplumber import integrity as int_mod

    monkeypatch.setattr(int_mod, "get_manifest_path", lambda: tmp_path / "manifests.json")
    monkeypatch.setattr(int_mod, "get_wireplumber_rule_dir", lambda: tmp_path / "wr")

    exit_code = cli.main(["wireplumber", "rule-state-doctor"])
    out = capsys.readouterr().out

    assert exit_code == 0
    assert "State Doctor" in out


def test_cli_repair_rule_state_exits_zero(tmp_path: Path, monkeypatch, capsys) -> None:
    from pipetune.wireplumber import integrity as int_mod

    monkeypatch.setattr(int_mod, "get_manifest_path", lambda: tmp_path / "manifests.json")
    monkeypatch.setattr(int_mod, "get_wireplumber_rule_dir", lambda: tmp_path / "wr")

    exit_code = cli.main(["wireplumber", "repair-rule-state", "--dry-run"])
    out = capsys.readouterr().out

    assert exit_code == 0
    assert "Dry run only" in out


def test_cli_cleanup_dry_run_exits_zero(tmp_path: Path, monkeypatch, capsys) -> None:
    from pipetune.wireplumber import integrity as int_mod

    monkeypatch.setattr(int_mod, "get_manifest_path", lambda: tmp_path / "manifests.json")

    exit_code = cli.main(["wireplumber", "cleanup-rolled-back-rules", "--dry-run"])
    out = capsys.readouterr().out

    assert exit_code == 0
    assert "Cleanup" in out or "cleanup" in out.lower()


# ---------------------------------------------------------------------------
# Safety: no system write, no restart, no routing
# ---------------------------------------------------------------------------

def test_no_systemctl_in_integrity_module() -> None:
    import inspect
    from pipetune.wireplumber import integrity

    src = inspect.getsource(integrity)
    assert "systemctl" not in src
    assert "wpctl set-default" not in src
    assert "pactl set-default-sink" not in src
    assert "pactl set-card-profile" not in src
