"""Tests for v0.9.0 WirePlumber rule install/rollback/state commands."""
from __future__ import annotations

import json
import os
from pathlib import Path

import pytest

import pipetune
from pipetune import cli
from pipetune.wireplumber.install import InstallReport, run_install_rule
from pipetune.wireplumber.manifest import load_manifest, save_manifest, RuleManifestEntry
from pipetune.wireplumber.rollback import run_rollback_rule
from pipetune.wireplumber.state import run_list_rules, run_rule_status


_VALID_PREVIEW_CONTENT = """\
-- PREVIEW ONLY — NOT INSTALLED
-- Generated by PipeTune Linux
-- This file is a skeleton for manual review only.
rule = {
  matches = {},
  apply_properties = {},
}
"""


def _make_preview(tmp_path: Path, name: str = "test-rule.lua", content: str = _VALID_PREVIEW_CONTENT) -> Path:
    p = tmp_path / "previews" / "wireplumber" / name
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")
    return p


def _isolated_dirs(tmp_path: Path) -> tuple[Path, Path]:
    """Return (rule_dir, manifest_path) under tmp_path."""
    rule_dir = tmp_path / "config" / "wireplumber" / "wireplumber.conf.d"
    manifest_path = tmp_path / "state" / "wireplumber-rules" / "manifests.json"
    return rule_dir, manifest_path


# ---------------------------------------------------------------------------
# Version check
# ---------------------------------------------------------------------------

def test_version_is_091() -> None:
    assert pipetune.__version__ == "0.9.1"


# ---------------------------------------------------------------------------
# install-rule: flag validation
# ---------------------------------------------------------------------------

def test_install_rule_requires_user_only(tmp_path: Path) -> None:
    preview = _make_preview(tmp_path)
    rule_dir, manifest_path = _isolated_dirs(tmp_path)

    report = run_install_rule(
        str(preview), user_only=False, dry_run=True, confirm_install=False,
        rule_dir=rule_dir, manifest_path=manifest_path,
    )

    assert report.passed is False
    assert any("--user-only" in e for e in report.errors)


def test_install_rule_refuses_both_dry_run_and_confirm(tmp_path: Path) -> None:
    preview = _make_preview(tmp_path)
    rule_dir, manifest_path = _isolated_dirs(tmp_path)

    report = run_install_rule(
        str(preview), user_only=True, dry_run=True, confirm_install=True,
        rule_dir=rule_dir, manifest_path=manifest_path,
    )

    assert report.passed is False
    assert any("Cannot pass both" in e for e in report.errors)


def test_install_rule_refuses_neither_flag(tmp_path: Path) -> None:
    preview = _make_preview(tmp_path)
    rule_dir, manifest_path = _isolated_dirs(tmp_path)

    report = run_install_rule(
        str(preview), user_only=True, dry_run=False, confirm_install=False,
        rule_dir=rule_dir, manifest_path=manifest_path,
    )

    assert report.passed is False
    assert any("Must pass either" in e for e in report.errors)


# ---------------------------------------------------------------------------
# install-rule: path safety
# ---------------------------------------------------------------------------

def test_install_rule_refuses_system_path_etc(tmp_path: Path) -> None:
    rule_dir, manifest_path = _isolated_dirs(tmp_path)

    report = run_install_rule(
        "/etc/wireplumber/bad-rule.lua", user_only=True, dry_run=True, confirm_install=False,
        rule_dir=rule_dir, manifest_path=manifest_path,
    )

    assert report.passed is False
    assert any("system path" in e for e in report.errors)


def test_install_rule_refuses_missing_preview_file(tmp_path: Path) -> None:
    rule_dir, manifest_path = _isolated_dirs(tmp_path)

    report = run_install_rule(
        str(tmp_path / "nonexistent.lua"), user_only=True, dry_run=True, confirm_install=False,
        rule_dir=rule_dir, manifest_path=manifest_path,
    )

    assert report.passed is False
    assert any("not found" in e for e in report.errors)


def test_install_rule_refuses_missing_safety_marker(tmp_path: Path) -> None:
    preview = _make_preview(tmp_path, content="-- No safety markers here\nrule = {}\n")
    rule_dir, manifest_path = _isolated_dirs(tmp_path)

    report = run_install_rule(
        str(preview), user_only=True, dry_run=True, confirm_install=False,
        rule_dir=rule_dir, manifest_path=manifest_path,
    )

    assert report.passed is False
    assert any("missing required safety marker" in e for e in report.errors)


# ---------------------------------------------------------------------------
# install-rule: dry-run writes nothing
# ---------------------------------------------------------------------------

def test_install_rule_dry_run_writes_nothing(tmp_path: Path) -> None:
    preview = _make_preview(tmp_path)
    rule_dir, manifest_path = _isolated_dirs(tmp_path)

    report = run_install_rule(
        str(preview), user_only=True, dry_run=True, confirm_install=False,
        rule_dir=rule_dir, manifest_path=manifest_path,
    )

    assert report.passed is True
    assert report.dry_run is True
    assert not rule_dir.exists() or not list(rule_dir.iterdir())
    assert not manifest_path.exists()
    assert any("Dry run" in w for w in report.warnings)


# ---------------------------------------------------------------------------
# install-rule: confirmed install writes only under isolated root
# ---------------------------------------------------------------------------

def test_install_rule_confirmed_install_writes_rule_and_manifest(tmp_path: Path) -> None:
    preview = _make_preview(tmp_path)
    rule_dir, manifest_path = _isolated_dirs(tmp_path)

    report = run_install_rule(
        str(preview), user_only=True, dry_run=False, confirm_install=True,
        rule_dir=rule_dir, manifest_path=manifest_path,
    )

    assert report.passed is True
    assert report.dry_run is False
    assert report.install_id
    assert report.rule_id.startswith("pipetune-rule-")
    # Rule file written under isolated rule_dir
    assert rule_dir.exists()
    installed_files = list(rule_dir.glob("90-pipetune-*.lua"))
    assert len(installed_files) == 1
    # Manifest written
    assert manifest_path.exists()
    entries = load_manifest(manifest_path)
    assert len(entries) == 1
    assert entries[0].install_id == report.install_id
    assert entries[0].status == "active"


def test_install_rule_confirmed_produces_install_id(tmp_path: Path) -> None:
    preview = _make_preview(tmp_path)
    rule_dir, manifest_path = _isolated_dirs(tmp_path)

    report = run_install_rule(
        str(preview), user_only=True, dry_run=False, confirm_install=True,
        rule_dir=rule_dir, manifest_path=manifest_path,
    )

    assert len(report.install_id) == 8
    assert report.install_id.isalnum()


def test_install_rule_warns_about_no_service_restart(tmp_path: Path) -> None:
    preview = _make_preview(tmp_path)
    rule_dir, manifest_path = _isolated_dirs(tmp_path)

    report = run_install_rule(
        str(preview), user_only=True, dry_run=False, confirm_install=True,
        rule_dir=rule_dir, manifest_path=manifest_path,
    )

    assert any("No service was restarted" in w for w in report.warnings)


# ---------------------------------------------------------------------------
# install-rule: JSON output
# ---------------------------------------------------------------------------

def test_install_rule_json_output_parses(tmp_path: Path) -> None:
    from pipetune.wireplumber.install import render_install_report_json

    preview = _make_preview(tmp_path)
    rule_dir, manifest_path = _isolated_dirs(tmp_path)

    report = run_install_rule(
        str(preview), user_only=True, dry_run=True, confirm_install=False,
        rule_dir=rule_dir, manifest_path=manifest_path,
    )
    data = json.loads(render_install_report_json(report))

    assert data["dry_run"] is True
    assert data["passed"] is True
    assert data["safety"]["restarted_services"] is False
    assert data["safety"]["changed_routing"] is False
    assert data["safety"]["system_level"] is False


# ---------------------------------------------------------------------------
# rollback-rule: flag validation
# ---------------------------------------------------------------------------

def test_rollback_rule_refuses_both_flags(tmp_path: Path) -> None:
    _, manifest_path = _isolated_dirs(tmp_path)

    report = run_rollback_rule("abc12345", dry_run=True, confirm_rollback=True, manifest_path=manifest_path)

    assert report.passed is False
    assert any("Cannot pass both" in e for e in report.errors)


def test_rollback_rule_refuses_neither_flag(tmp_path: Path) -> None:
    _, manifest_path = _isolated_dirs(tmp_path)

    report = run_rollback_rule("abc12345", dry_run=False, confirm_rollback=False, manifest_path=manifest_path)

    assert report.passed is False
    assert any("Must pass either" in e for e in report.errors)


def test_rollback_rule_unknown_id_fails_cleanly(tmp_path: Path) -> None:
    _, manifest_path = _isolated_dirs(tmp_path)

    report = run_rollback_rule("unknown0", dry_run=True, confirm_rollback=False, manifest_path=manifest_path)

    assert report.passed is False
    assert any("Unknown install_id" in e for e in report.errors)


def test_rollback_rule_already_rolled_back_fails_cleanly(tmp_path: Path) -> None:
    rule_dir, manifest_path = _isolated_dirs(tmp_path)
    preview = _make_preview(tmp_path)

    install_report = run_install_rule(
        str(preview), user_only=True, dry_run=False, confirm_install=True,
        rule_dir=rule_dir, manifest_path=manifest_path,
    )
    install_id = install_report.install_id
    run_rollback_rule(install_id, dry_run=False, confirm_rollback=True, manifest_path=manifest_path)

    report = run_rollback_rule(install_id, dry_run=False, confirm_rollback=True, manifest_path=manifest_path)

    assert report.passed is False
    assert any("already rolled back" in e for e in report.errors)


# ---------------------------------------------------------------------------
# rollback-rule: dry-run writes nothing
# ---------------------------------------------------------------------------

def test_rollback_rule_dry_run_writes_nothing(tmp_path: Path) -> None:
    rule_dir, manifest_path = _isolated_dirs(tmp_path)
    preview = _make_preview(tmp_path)

    install_report = run_install_rule(
        str(preview), user_only=True, dry_run=False, confirm_install=True,
        rule_dir=rule_dir, manifest_path=manifest_path,
    )
    install_id = install_report.install_id
    installed_files_before = list(rule_dir.glob("*.lua"))

    report = run_rollback_rule(install_id, dry_run=True, confirm_rollback=False, manifest_path=manifest_path)

    assert report.passed is True
    assert report.dry_run is True
    # File still present after dry-run
    assert list(rule_dir.glob("*.lua")) == installed_files_before
    # Manifest entry still active
    entries = load_manifest(manifest_path)
    assert any(e.install_id == install_id and e.status == "active" for e in entries)


# ---------------------------------------------------------------------------
# rollback-rule: confirmed rollback removes file and updates manifest
# ---------------------------------------------------------------------------

def test_rollback_rule_confirmed_removes_file_and_updates_manifest(tmp_path: Path) -> None:
    rule_dir, manifest_path = _isolated_dirs(tmp_path)
    preview = _make_preview(tmp_path)

    install_report = run_install_rule(
        str(preview), user_only=True, dry_run=False, confirm_install=True,
        rule_dir=rule_dir, manifest_path=manifest_path,
    )
    install_id = install_report.install_id

    report = run_rollback_rule(install_id, dry_run=False, confirm_rollback=True, manifest_path=manifest_path)

    assert report.passed is True
    assert not list(rule_dir.glob("*.lua"))
    entries = load_manifest(manifest_path)
    assert any(e.install_id == install_id and e.status == "rolled_back" for e in entries)


def test_rollback_rule_handles_already_missing_file(tmp_path: Path) -> None:
    rule_dir, manifest_path = _isolated_dirs(tmp_path)
    preview = _make_preview(tmp_path)

    install_report = run_install_rule(
        str(preview), user_only=True, dry_run=False, confirm_install=True,
        rule_dir=rule_dir, manifest_path=manifest_path,
    )
    install_id = install_report.install_id
    for f in rule_dir.glob("*.lua"):
        f.unlink()

    report = run_rollback_rule(install_id, dry_run=False, confirm_rollback=True, manifest_path=manifest_path)

    assert report.passed is True
    entries = load_manifest(manifest_path)
    assert any(e.install_id == install_id and e.status == "rolled_back" for e in entries)
    assert any("already missing" in w for w in report.warnings)


# ---------------------------------------------------------------------------
# rollback-rule: JSON output
# ---------------------------------------------------------------------------

def test_rollback_rule_json_output_parses(tmp_path: Path) -> None:
    from pipetune.wireplumber.rollback import render_rollback_report_json

    rule_dir, manifest_path = _isolated_dirs(tmp_path)
    preview = _make_preview(tmp_path)

    install_report = run_install_rule(
        str(preview), user_only=True, dry_run=False, confirm_install=True,
        rule_dir=rule_dir, manifest_path=manifest_path,
    )

    report = run_rollback_rule(
        install_report.install_id, dry_run=True, confirm_rollback=False, manifest_path=manifest_path
    )
    data = json.loads(render_rollback_report_json(report))

    assert data["safety"]["restarted_services"] is False
    assert data["safety"]["changed_routing"] is False


# ---------------------------------------------------------------------------
# rule-status / list-rules: read-only
# ---------------------------------------------------------------------------

def test_rule_status_read_only_no_manifest(tmp_path: Path) -> None:
    _, manifest_path = _isolated_dirs(tmp_path)

    report = run_rule_status(manifest_path=manifest_path)

    assert report.active_count == 0
    assert report.rolled_back_count == 0
    assert report.broken_count == 0
    assert report.verdict in ("pass", "warn")


def test_list_rules_read_only_empty(tmp_path: Path) -> None:
    _, manifest_path = _isolated_dirs(tmp_path)

    report = run_list_rules(manifest_path=manifest_path)

    assert report.entries == []
    assert report.verdict in ("pass", "warn")


def test_rule_status_reflects_installed_rules(tmp_path: Path) -> None:
    rule_dir, manifest_path = _isolated_dirs(tmp_path)
    preview = _make_preview(tmp_path)
    run_install_rule(
        str(preview), user_only=True, dry_run=False, confirm_install=True,
        rule_dir=rule_dir, manifest_path=manifest_path,
    )

    report = run_rule_status(manifest_path=manifest_path)

    assert report.active_count == 1
    assert report.rolled_back_count == 0


def test_rule_status_json_parses(tmp_path: Path) -> None:
    from pipetune.wireplumber.state import render_rule_status_json

    _, manifest_path = _isolated_dirs(tmp_path)
    report = run_rule_status(manifest_path=manifest_path)
    data = json.loads(render_rule_status_json(report))

    assert data["safety"]["read_only"] is True
    assert "active_count" in data
    assert "entries" in data


def test_list_rules_json_parses(tmp_path: Path) -> None:
    from pipetune.wireplumber.state import render_list_rules_json

    _, manifest_path = _isolated_dirs(tmp_path)
    report = run_list_rules(manifest_path=manifest_path)
    data = json.loads(render_list_rules_json(report))

    assert data["safety"]["read_only"] is True
    assert "entries" in data


# ---------------------------------------------------------------------------
# CLI integration
# ---------------------------------------------------------------------------

def test_cli_install_rule_dry_run(tmp_path: Path, monkeypatch, capsys) -> None:
    preview = _make_preview(tmp_path)
    rule_dir, manifest_path = _isolated_dirs(tmp_path)

    from pipetune.wireplumber import install as inst_mod, paths as paths_mod

    monkeypatch.setattr(inst_mod, "get_wireplumber_rule_dir", lambda: rule_dir)
    monkeypatch.setattr(inst_mod, "get_manifest_path", lambda: manifest_path)

    exit_code = cli.main([
        "wireplumber", "install-rule", str(preview),
        "--user-only", "--dry-run",
    ])
    out = capsys.readouterr().out

    assert exit_code == 0
    assert "Dry" in out or "dry" in out
    assert "No service was restarted" in out


def test_cli_rule_status_exits_zero(tmp_path: Path, monkeypatch, capsys) -> None:
    _, manifest_path = _isolated_dirs(tmp_path)

    from pipetune.wireplumber import state as state_mod

    monkeypatch.setattr(state_mod, "get_manifest_path", lambda: manifest_path)
    monkeypatch.setattr(state_mod, "get_wireplumber_rule_dir", lambda: tmp_path / "wr")

    exit_code = cli.main(["wireplumber", "rule-status"])
    out = capsys.readouterr().out

    assert exit_code == 0
    assert "WirePlumber Rule Status" in out


def test_cli_list_rules_exits_zero(tmp_path: Path, monkeypatch, capsys) -> None:
    _, manifest_path = _isolated_dirs(tmp_path)

    from pipetune.wireplumber import state as state_mod

    monkeypatch.setattr(state_mod, "get_manifest_path", lambda: manifest_path)
    monkeypatch.setattr(state_mod, "get_wireplumber_rule_dir", lambda: tmp_path / "wr")

    exit_code = cli.main(["wireplumber", "list-rules"])
    out = capsys.readouterr().out

    assert exit_code == 0
    assert "This command is read-only" in out


# ---------------------------------------------------------------------------
# Safety: no system write, no service restart, no routing
# ---------------------------------------------------------------------------

def test_install_confirmed_does_not_write_outside_isolated_root(tmp_path: Path) -> None:
    preview = _make_preview(tmp_path)
    rule_dir, manifest_path = _isolated_dirs(tmp_path)

    report = run_install_rule(
        str(preview), user_only=True, dry_run=False, confirm_install=True,
        rule_dir=rule_dir, manifest_path=manifest_path,
    )

    assert report.passed is True
    installed = Path(report.destination_path)
    assert str(installed).startswith(str(rule_dir))


def test_no_systemctl_or_routing_calls_in_install_modules() -> None:
    import inspect
    from pipetune.wireplumber import install, rollback, state
    for module in (install, rollback, state):
        src = inspect.getsource(module)
        assert "systemctl" not in src, f"systemctl found in {module.__name__}"
        assert "wpctl set-default" not in src, f"wpctl set-default found in {module.__name__}"
        assert "pactl set-default-sink" not in src
        assert "pactl set-card-profile" not in src
