from __future__ import annotations

from pathlib import Path

from pipetune.safety.manifest import create_profile_manifest
from pipetune.safety.models import HardwareQuirkMetadata
from pipetune.safety.preflight import run_profile_preflight, run_profile_safety_check


def _config_text(gain: float = 2.0) -> str:
    return f"""
# PipeTune Linux generated PipeWire filter-chain configuration
# Profile: Sennheiser HD 650
# Source AutoEQ file: examples/autoeq/sennheiser-hd650.txt
# Generated by PipeTune Linux v0.2.5
# Preamp: -6.8 dB
context.modules = [
  {{
    name = libpipewire-module-filter-chain
    args = {{
      filter.graph = {{
        nodes = [
          {{
            type = builtin
            name = eq_1
            label = bq_peaking
            control = {{ "Freq" = 1000 "Q" = 1 "Gain" = {gain:g} }}
          }}
        ]
      }}
    }}
  }}
]
"""


def _quirk_detected() -> HardwareQuirkMetadata:
    return HardwareQuirkMetadata(
        quirk_detected=True,
        quirk_type="manual_hda_pin_retask",
        auto_switch_safe=False,
        built_in_microphone_reliable=None,
        requires_manual_output_confirmation=True,
        evidence=["hda-jack-retask references detected"],
        warnings=["Do not auto-apply speaker/headphone profiles without manual confirmation."],
    )


def _no_quirk() -> HardwareQuirkMetadata:
    return HardwareQuirkMetadata(
        quirk_detected=False,
        quirk_type="none",
        auto_switch_safe=True,
        built_in_microphone_reliable=None,
        requires_manual_output_confirmation=False,
        evidence=["No HDA retask indicator detected."],
        warnings=[],
    )


def test_safety_check_detects_pipetune_generated_config(tmp_path: Path) -> None:
    config = tmp_path / "hd650.filter-chain.conf"
    config.write_text(_config_text(), encoding="utf-8")

    check = run_profile_safety_check(config)

    assert check.appears_generated_by_pipetune is True
    assert check.filter_chain_config is True
    assert check.filter_count == 1


def test_safety_check_reports_missing_manifest_as_warning(tmp_path: Path) -> None:
    config = tmp_path / "hd650.filter-chain.conf"
    config.write_text(_config_text(), encoding="utf-8")

    check = run_profile_safety_check(config)

    assert check.manifest_present is False
    assert "Manifest is missing." in check.warnings
    assert check.errors == []


def test_preflight_requires_confirmation_when_hda_quirk_detected(monkeypatch, tmp_path: Path) -> None:
    config = tmp_path / "hd650.filter-chain.conf"
    config.write_text(_config_text(), encoding="utf-8")
    create_profile_manifest(config, "Sennheiser HD 650", "headphone")
    monkeypatch.setattr("pipetune.safety.preflight.collect_hardware_quirk_metadata", _quirk_detected)

    result = run_profile_preflight(config)

    assert result.readiness.status == "requires_confirmation"
    assert "Hardware quirk detected on this machine." in result.readiness.reasons


def test_preflight_blocked_for_missing_config(monkeypatch, tmp_path: Path) -> None:
    monkeypatch.setattr("pipetune.safety.preflight.collect_hardware_quirk_metadata", _no_quirk)

    result = run_profile_preflight(tmp_path / "missing.filter-chain.conf")

    assert result.readiness.status == "blocked"
    assert any("Config file not found" in reason for reason in result.readiness.reasons)


def test_preflight_unknown_when_manifest_missing(monkeypatch, tmp_path: Path) -> None:
    config = tmp_path / "hd650.filter-chain.conf"
    config.write_text(_config_text(), encoding="utf-8")
    monkeypatch.setattr("pipetune.safety.preflight.collect_hardware_quirk_metadata", _no_quirk)

    result = run_profile_preflight(config)

    assert result.readiness.status == "unknown"
    assert "Manifest is missing." in result.readiness.reasons
