from __future__ import annotations

from pathlib import Path

from pipetune.activation.installer import install_profile, render_install_result
from pipetune.safety.manifest import create_profile_manifest
from pipetune.safety.models import ActivationReadiness, HardwareQuirkMetadata, ProfilePreflightResult


def _config(tmp_path: Path) -> Path:
    config = tmp_path / "safe.filter-chain.conf"
    config.write_text(
        """
# PipeTune Linux generated PipeWire filter-chain configuration
# Profile: Safe
# Generated by PipeTune Linux v0.3.0
# Preamp: -3 dB
context.modules = [{ name = libpipewire-module-filter-chain args = { filter.graph = { nodes = [
{ type = builtin name = eq_1 label = bq_peaking control = { "Gain" = 1 } }
] } } }]
""",
        encoding="utf-8",
    )
    create_profile_manifest(config, "Safe", "headphone")
    return config


def _preflight(status: str) -> ProfilePreflightResult:
    return ProfilePreflightResult(
        profile_name="Safe",
        profile_type="headphone",
        config_path="safe.filter-chain.conf",
        manifest_path="safe.filter-chain.manifest.json",
        manifest_present=True,
        hardware_quirk=HardwareQuirkMetadata(
            quirk_detected=status == "requires_confirmation",
            quirk_type="manual_hda_pin_retask" if status == "requires_confirmation" else "none",
            auto_switch_safe=status != "requires_confirmation",
            built_in_microphone_reliable=None,
            requires_manual_output_confirmation=status == "requires_confirmation",
            evidence=[],
            warnings=[],
        ),
        readiness=ActivationReadiness(status=status, reasons=[], warnings=[], recommended_next_steps=[]),
    )


def test_blocked_preflight_refuses_install(monkeypatch, tmp_path: Path) -> None:
    monkeypatch.setenv("PIPETUNE_HOME", str(tmp_path / "home"))
    monkeypatch.setattr("pipetune.activation.installer.run_profile_preflight", lambda _config: _preflight("blocked"))

    result = install_profile(_config(tmp_path), user_level=True, confirm_install=True, confirm_hardware_quirk=False)

    assert result.success is False
    assert "blocked" in result.errors[0]


def test_requires_confirmation_refuses_without_hardware_confirmation(monkeypatch, tmp_path: Path) -> None:
    monkeypatch.setenv("PIPETUNE_HOME", str(tmp_path / "home"))
    monkeypatch.setattr(
        "pipetune.activation.installer.run_profile_preflight", lambda _config: _preflight("requires_confirmation")
    )

    result = install_profile(_config(tmp_path), user_level=True, confirm_install=True, confirm_hardware_quirk=False)

    assert result.success is False
    assert "--confirm-hardware-quirk" in result.errors[0]


def test_requires_confirmation_succeeds_with_hardware_confirmation(monkeypatch, tmp_path: Path) -> None:
    monkeypatch.setenv("PIPETUNE_HOME", str(tmp_path / "home"))
    monkeypatch.setattr(
        "pipetune.activation.installer.run_profile_preflight", lambda _config: _preflight("requires_confirmation")
    )

    result = install_profile(_config(tmp_path), user_level=True, confirm_install=True, confirm_hardware_quirk=True)

    assert result.success is True
    assert result.hardware_quirk_confirmed is True


def test_install_prints_hardware_quirk_warning(monkeypatch, tmp_path: Path) -> None:
    monkeypatch.setenv("PIPETUNE_HOME", str(tmp_path / "home"))
    monkeypatch.setattr(
        "pipetune.activation.installer.run_profile_preflight", lambda _config: _preflight("requires_confirmation")
    )

    output = render_install_result(
        install_profile(_config(tmp_path), user_level=True, confirm_install=True, confirm_hardware_quirk=True)
    )

    assert "Hardware quirk detected. Verify physical output target manually before restarting PipeWire." in output
