from __future__ import annotations

from pathlib import Path

from pipetune import cli
from pipetune.activation.installer import install_profile
from pipetune.activation.manifest import list_install_manifests
from pipetune.activation.paths import user_pipewire_config_dir
from pipetune.activation.rollback import rollback_profile
from pipetune.activation.state import build_state_doctor_report
from pipetune.activation.status import cleanup_rolled_back_manifests, render_repair_state_dry_run
from pipetune.safety.manifest import create_profile_manifest
from pipetune.safety.models import ActivationReadiness, HardwareQuirkMetadata, ProfilePreflightResult


def _preflight() -> ProfilePreflightResult:
    return ProfilePreflightResult(
        profile_name="Integrity",
        profile_type="headphone",
        config_path="integrity.filter-chain.conf",
        manifest_path="integrity.filter-chain.manifest.json",
        manifest_present=True,
        hardware_quirk=HardwareQuirkMetadata(False, "none", True, None, False, [], []),
        readiness=ActivationReadiness("ready", [], [], []),
    )


def _config(tmp_path: Path, *, name: str = "integrity") -> Path:
    config = tmp_path / f"{name}.filter-chain.conf"
    config.write_text(
        f"""
# PipeTune Linux generated PipeWire filter-chain configuration
# Profile: {name}
# Generated by PipeTune Linux v0.3.1
# Preamp: -3 dB
context.modules = [{{ name = libpipewire-module-filter-chain args = {{ filter.graph = {{ nodes = [
{{ type = builtin name = eq_1 label = bq_peaking control = {{ "Gain" = 1 }} }}
] }} }} }}]
""",
        encoding="utf-8",
    )
    create_profile_manifest(config, name, "headphone")
    return config


def _install(monkeypatch, tmp_path: Path, *, name: str = "integrity"):
    monkeypatch.setenv("PIPETUNE_HOME", str(tmp_path / "home"))
    monkeypatch.setattr("pipetune.activation.installer.run_profile_preflight", lambda _config: _preflight())
    return install_profile(
        _config(tmp_path, name=name),
        user_level=True,
        confirm_install=True,
        confirm_hardware_quirk=False,
    )


def test_duplicate_install_does_not_create_duplicate_active_entries(monkeypatch, tmp_path: Path) -> None:
    first = _install(monkeypatch, tmp_path)
    second = install_profile(
        _config(tmp_path),
        user_level=True,
        confirm_install=True,
        confirm_hardware_quirk=False,
    )

    assert first.success is True
    assert second.success is False
    assert "already installed and active" in second.errors[0]
    active = [manifest for _path, manifest in list_install_manifests() if manifest.rollback_status == "active"]
    assert len(active) == 1


def test_missing_config_is_reported_by_state_doctor(monkeypatch, tmp_path: Path) -> None:
    result = _install(monkeypatch, tmp_path)
    assert result.destination_path is not None
    Path(result.destination_path).unlink()

    report = build_state_doctor_report()

    assert report.missing_config_count == 1
    assert report.verdict == "warn"


def test_orphan_config_is_reported_by_state_doctor(monkeypatch, tmp_path: Path) -> None:
    monkeypatch.setenv("PIPETUNE_HOME", str(tmp_path / "home"))
    config_dir = user_pipewire_config_dir()
    config_dir.mkdir(parents=True, exist_ok=True)
    (config_dir / "90-pipetune-orphan.conf").write_text("orphan", encoding="utf-8")

    report = build_state_doctor_report()

    assert report.orphan_config_count == 1
    assert "90-pipetune-orphan.conf" in report.orphan_configs[0]


def test_checksum_mismatch_is_detected(monkeypatch, tmp_path: Path) -> None:
    result = _install(monkeypatch, tmp_path)
    assert result.destination_path is not None
    Path(result.destination_path).write_text("modified", encoding="utf-8")

    report = build_state_doctor_report()

    assert report.checksum_mismatch_count == 1
    assert report.verdict == "fail"


def test_rollback_invalid_id_fails_cleanly(monkeypatch, tmp_path: Path) -> None:
    monkeypatch.setenv("PIPETUNE_HOME", str(tmp_path / "home"))

    result = rollback_profile(install_id="missing-id", confirm_rollback=True)

    assert result.success is False
    assert "Unknown install ID: missing-id" in result.errors


def test_rollback_already_rolled_back_id_fails_cleanly(monkeypatch, tmp_path: Path) -> None:
    install = _install(monkeypatch, tmp_path)
    rollback_profile(install_id=install.install_id, confirm_rollback=True)

    result = rollback_profile(install_id=install.install_id, confirm_rollback=True)

    assert result.success is False
    assert "already rolled back" in result.errors[0]


def test_repair_state_dry_run_changes_nothing(monkeypatch, tmp_path: Path) -> None:
    _install(monkeypatch, tmp_path)
    before = len(list_install_manifests())

    output = render_repair_state_dry_run()
    after = len(list_install_manifests())

    assert "Dry run only. No files were modified." in output
    assert before == after


def test_cleanup_rolled_back_removes_only_safe_rolled_back_manifest_entries(monkeypatch, tmp_path: Path) -> None:
    rolled_back = _install(monkeypatch, tmp_path, name="rolled")
    rollback_profile(install_id=rolled_back.install_id, confirm_rollback=True)
    active = _install(monkeypatch, tmp_path, name="active")

    output, exit_code = cleanup_rolled_back_manifests(confirm_cleanup=True)

    remaining = [manifest.install_id for _path, manifest in list_install_manifests()]
    assert exit_code == 0
    assert "Removed manifests: 1" in output
    assert rolled_back.install_id not in remaining
    assert active.install_id in remaining


def test_profile_state_doctor_command_exists() -> None:
    parser = cli._build_parser()
    args = parser.parse_args(["profile", "state-doctor"])

    assert args.profile_command == "state-doctor"


def test_profile_verify_install_invalid_id_returns_nonzero(monkeypatch, tmp_path: Path) -> None:
    monkeypatch.setenv("PIPETUNE_HOME", str(tmp_path / "home"))

    assert cli.main(["profile", "verify-install", "missing"]) == 1


def test_profile_repair_state_requires_dry_run() -> None:
    assert cli.main(["profile", "repair-state"]) == 1


def test_profile_cleanup_rolled_back_requires_confirmation() -> None:
    assert cli.main(["profile", "cleanup-rolled-back"]) == 1
