from __future__ import annotations

import json
import subprocess
from pathlib import Path

from pipetune import cli
from pipetune.safety.manifest import create_profile_manifest


def _generated_config() -> str:
    return """
# PipeTune Linux generated PipeWire filter-chain configuration
# Profile: Test Headphone
# Source format: AutoEQ
# Source AutoEQ file: examples/autoeq/test.txt
# Generated by PipeTune Linux v0.2.5
# Enabled filters: 1
# This file is generated only. It is not installed automatically.
# Preamp: -6.8 dB
context.modules = [
  {
    name = libpipewire-module-filter-chain
    args = {
      filter.graph = {
        nodes = [
          {
            type = builtin
            name = eq_1
            label = bq_peaking
            control = {
              "Freq" = 1000
              "Q" = 1
              "Gain" = 3
            }
          }
        ]
      }
    }
  }
]
"""


def test_profile_manifest_command_exists() -> None:
    parser = cli._build_parser()
    args = parser.parse_args(["profile", "manifest", "generated/test.filter-chain.conf", "--name", "Test", "--type", "headphone"])

    assert args.command == "profile"
    assert args.profile_command == "manifest"


def test_manifest_json_contains_required_keys(tmp_path: Path) -> None:
    config = tmp_path / "test.filter-chain.conf"
    config.write_text(_generated_config(), encoding="utf-8")

    manifest_path, manifest, errors = create_profile_manifest(config, "Test Headphone", "headphone")

    assert errors == []
    assert manifest_path is not None
    assert manifest is not None
    assert manifest["config_file"] == str(config)
    assert manifest["appears_generated_by_pipetune"] is True
    assert manifest["profile"]["profile_name"] == "Test Headphone"
    assert manifest["profile"]["profile_type"] == "headphone"
    assert manifest["profile"]["preamp_db"] == -6.8
    assert manifest["profile"]["enabled_filter_count"] == 1
    assert manifest["safety"]["requires_manual_output_confirmation"] is True
    assert json.loads(manifest_path.read_text(encoding="utf-8"))["schema_version"] == 1


def test_invalid_profile_type_fails(tmp_path: Path) -> None:
    config = tmp_path / "test.filter-chain.conf"
    config.write_text(_generated_config(), encoding="utf-8")

    manifest_path, manifest, errors = create_profile_manifest(config, "Test", "unsafe-speaker")

    assert manifest_path is None
    assert manifest is None
    assert "Invalid profile type" in errors[0]


def test_missing_config_file_fails_cleanly(tmp_path: Path) -> None:
    manifest_path, manifest, errors = create_profile_manifest(tmp_path / "missing.conf", "Test", "headphone")

    assert manifest_path is None
    assert manifest is None
    assert "Config file not found" in errors[0]


def test_generated_manifest_files_are_gitignored() -> None:
    completed = subprocess.run(
        ["git", "check-ignore", "-q", "generated/example.filter-chain.manifest.json"],
        check=False,
    )

    assert completed.returncode == 0
