from __future__ import annotations

from pathlib import Path

from pipetune import cli
from pipetune.activation.installer import install_profile
from pipetune.activation.manifest import list_install_manifests, sha256_file
from pipetune.activation.paths import user_pipewire_config_dir
from pipetune.safety.manifest import create_profile_manifest
from pipetune.safety.models import ActivationReadiness, HardwareQuirkMetadata, ProfilePreflightResult


def _config_text() -> str:
    return """
# PipeTune Linux generated PipeWire filter-chain configuration
# Profile: Test Headphone
# Source AutoEQ file: test.txt
# Generated by PipeTune Linux v0.3.0
# Preamp: -6 dB
context.modules = [
  { name = libpipewire-module-filter-chain args = { filter.graph = { nodes = [
    { type = builtin name = eq_1 label = bq_peaking control = { "Freq" = 1000 "Q" = 1 "Gain" = 1 } }
  ] } } }
]
"""


def _write_config_with_manifest(tmp_path: Path) -> Path:
    config = tmp_path / "test.filter-chain.conf"
    config.write_text(_config_text(), encoding="utf-8")
    create_profile_manifest(config, "Test Headphone", "headphone")
    return config


def _preflight(status: str = "ready") -> ProfilePreflightResult:
    return ProfilePreflightResult(
        profile_name="Test Headphone",
        profile_type="headphone",
        config_path="test.filter-chain.conf",
        manifest_path="test.filter-chain.manifest.json",
        manifest_present=True,
        hardware_quirk=HardwareQuirkMetadata(
            quirk_detected=False,
            quirk_type="none",
            auto_switch_safe=True,
            built_in_microphone_reliable=None,
            requires_manual_output_confirmation=False,
            evidence=[],
            warnings=[],
        ),
        readiness=ActivationReadiness(status=status, reasons=["ok"], warnings=[], recommended_next_steps=[]),
    )


def test_install_refuses_without_confirm_install(monkeypatch, tmp_path: Path) -> None:
    monkeypatch.setenv("PIPETUNE_HOME", str(tmp_path / "home"))
    config = _write_config_with_manifest(tmp_path)

    result = install_profile(config, user_level=True, confirm_install=False, confirm_hardware_quirk=False)

    assert result.success is False
    assert "Install requires --confirm-install." in result.errors


def test_install_refuses_without_user(monkeypatch, tmp_path: Path) -> None:
    monkeypatch.setenv("PIPETUNE_HOME", str(tmp_path / "home"))
    config = _write_config_with_manifest(tmp_path)

    result = install_profile(config, user_level=False, confirm_install=True, confirm_hardware_quirk=False)

    assert result.success is False
    assert "Install requires --user." in result.errors


def test_install_refuses_missing_config(monkeypatch, tmp_path: Path) -> None:
    monkeypatch.setenv("PIPETUNE_HOME", str(tmp_path / "home"))

    result = install_profile(tmp_path / "missing.conf", user_level=True, confirm_install=True, confirm_hardware_quirk=False)

    assert result.success is False
    assert "Config file not found" in result.errors[0]


def test_install_refuses_missing_manifest(monkeypatch, tmp_path: Path) -> None:
    monkeypatch.setenv("PIPETUNE_HOME", str(tmp_path / "home"))
    config = tmp_path / "test.filter-chain.conf"
    config.write_text(_config_text(), encoding="utf-8")

    result = install_profile(config, user_level=True, confirm_install=True, confirm_hardware_quirk=False)

    assert result.success is False
    assert "Manifest missing" in result.errors[0]


def test_install_succeeds_with_ready_preflight_and_confirmation(monkeypatch, tmp_path: Path) -> None:
    monkeypatch.setenv("PIPETUNE_HOME", str(tmp_path / "home"))
    monkeypatch.setattr("pipetune.activation.installer.run_profile_preflight", lambda _config: _preflight("ready"))
    config = _write_config_with_manifest(tmp_path)

    result = install_profile(config, user_level=True, confirm_install=True, confirm_hardware_quirk=False)

    assert result.success is True
    assert result.destination_path is not None
    installed = Path(result.destination_path)
    assert installed.exists()
    assert installed.read_text(encoding="utf-8") == config.read_text(encoding="utf-8")
    assert result.manifest_path is not None and Path(result.manifest_path).exists()
    manifest = list_install_manifests()[0][1]
    assert manifest.source_sha256 == sha256_file(config)
    assert manifest.installed_sha256 == sha256_file(installed)


def test_install_cli_does_not_restart_services(monkeypatch, tmp_path: Path, capsys) -> None:
    monkeypatch.setenv("PIPETUNE_HOME", str(tmp_path / "home"))
    monkeypatch.setattr("pipetune.activation.installer.run_profile_preflight", lambda _config: _preflight("ready"))
    config = _write_config_with_manifest(tmp_path)

    assert cli.main(["profile", "install", str(config), "--user", "--confirm-install"]) == 0
    output = capsys.readouterr().out

    assert "No services were restarted automatically." in output
    assert "systemctl --user restart pipewire pipewire-pulse wireplumber" in output


def test_install_writes_only_user_level_destination(monkeypatch, tmp_path: Path) -> None:
    monkeypatch.setenv("PIPETUNE_HOME", str(tmp_path / "home"))
    monkeypatch.setattr("pipetune.activation.installer.run_profile_preflight", lambda _config: _preflight("ready"))
    config = _write_config_with_manifest(tmp_path)

    result = install_profile(config, user_level=True, confirm_install=True, confirm_hardware_quirk=False)

    assert result.destination_path is not None
    assert Path(result.destination_path).parent == user_pipewire_config_dir()
