"""PipeWire filter-chain config generation from validated audio profiles."""

from __future__ import annotations

import re
from pathlib import Path

from pipetune import __version__
from pipetune.profile.models import AudioProfile, ProfileValidationResult
from pipetune.profile.validator import validate_profile

_TYPE_TO_LABEL = {
    "PK": "bq_peaking",
    "PEAK": "bq_peaking",
    "PEAKING": "bq_peaking",
    "LS": "bq_lowshelf",
    "LOW_SHELF": "bq_lowshelf",
    "LOWSHELF": "bq_lowshelf",
    "HS": "bq_highshelf",
    "HIGH_SHELF": "bq_highshelf",
    "HIGHSHELF": "bq_highshelf",
}


def sanitize_profile_name(name: str) -> str:
    slug = name.strip().lower()
    slug = re.sub(r"\s+", "-", slug)
    slug = re.sub(r"[^a-z0-9_-]", "", slug)
    slug = re.sub(r"-+", "-", slug).strip("-_")

    if not slug:
        slug = "profile"

    return f"{slug}.filter-chain.conf"


def _filter_label(filter_type: str) -> str | None:
    return _TYPE_TO_LABEL.get(filter_type.strip().replace("-", "_").upper())


def generate_pipewire_filter_chain_config(profile: AudioProfile, source_file: Path) -> str:
    validation: ProfileValidationResult = validate_profile(profile)
    if not validation.valid:
        raise ValueError("Profile validation failed. Refusing to generate PipeWire config.")

    enabled_filters = [item for item in profile.filters if item.enabled]

    lines: list[str] = [
        "# PipeTune Linux generated PipeWire filter-chain configuration",
        f"# Profile: {profile.name}",
        "# Profile type: unknown",
        "# Source format: AutoEQ",
        f"# Source AutoEQ file: {source_file}",
        f"# Generated by PipeTune Linux v{__version__}",
        f"# Enabled filters: {len(enabled_filters)}",
        "# This file is generated only. It is not installed automatically.",
        "#",
    ]

    if profile.preamp_db is not None:
        lines.append(f"# Preamp: {profile.preamp_db:g} dB")
        lines.append(
            "# Apply this as input gain before the EQ chain if your PipeWire filter-chain setup supports it."
        )
    else:
        lines.append("# No preamp value was provided in the source AutoEQ file.")

    lines.extend(
        [
            "",
            "context.modules = [",
            "  {",
            "    name = libpipewire-module-filter-chain",
            "    args = {",
            f"      node.description = \"PipeTune EQ: {profile.name}\"",
            f"      media.name = \"PipeTune EQ: {profile.name}\"",
            "      filter.graph = {",
            "        nodes = [",
        ]
    )

    for filter_item in enabled_filters:
        label = _filter_label(filter_item.filter_type)
        if not label:
            continue
        lines.extend(
            [
                "          {",
                "            type = builtin",
                f"            name = eq_{filter_item.index}",
                f"            label = {label}",
                "            control = {",
                f"              \"Freq\" = {filter_item.frequency_hz:g}",
                f"              \"Q\" = {filter_item.q:g}",
                f"              \"Gain\" = {filter_item.gain_db:g}",
                "            }",
                "          }",
            ]
        )

    lines.extend(["        ]", "        links = ["])

    for left, right in zip(enabled_filters, enabled_filters[1:]):
        left_label = _filter_label(left.filter_type)
        right_label = _filter_label(right.filter_type)
        if not left_label or not right_label:
            continue
        lines.append(f"          {{ output = \"eq_{left.index}:Out\" input = \"eq_{right.index}:In\" }}")

    lines.append("        ]")

    if enabled_filters:
        first_filter = enabled_filters[0]
        last_filter = enabled_filters[-1]
        lines.append(f"        inputs  = [ \"eq_{first_filter.index}:In\" ]")
        lines.append(f"        outputs = [ \"eq_{last_filter.index}:Out\" ]")
    else:
        lines.append("        # No enabled filters were provided.")
        lines.append("        inputs  = [ ]")
        lines.append("        outputs = [ ]")

    lines.extend(
        [
            "      }",
            "      capture.props = {",
            "        node.name = \"pipetune.eq.capture\"",
            "        media.class = \"Audio/Sink\"",
            "      }",
            "      playback.props = {",
            "        node.name = \"pipetune.eq.playback\"",
            "        media.class = \"Audio/Source\"",
            "      }",
            "    }",
            "  }",
            "]",
            "",
        ]
    )

    return "\n".join(lines)


def write_generated_config(profile: AudioProfile, source_file: Path, output_dir: Path) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    filename = sanitize_profile_name(profile.name)
    output_path = output_dir / filename
    output_path.write_text(generate_pipewire_filter_chain_config(profile, source_file), encoding="utf-8")
    return output_path
