"""Profile safety metadata construction."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
import re

from pipetune import __version__
from pipetune.safety.models import ALLOWED_PROFILE_TYPES, ProfileSafetyMetadata

_GAIN_RE = re.compile(r'"Gain"\s*=\s*([+-]?\d+(?:\.\d+)?)')
_LABEL_RE = re.compile(r"\blabel\s*=\s*([A-Za-z0-9_:-]+)")
_PREAMP_RE = re.compile(r"#\s*(?:Preamp from AutoEQ|Preamp)\s*:\s*([+-]?\d+(?:\.\d+)?)\s*dB", re.IGNORECASE)
_SOURCE_FILE_RE = re.compile(r"#\s*Source AutoEQ file:\s*(.+)")


def validate_profile_type(profile_type: str) -> bool:
    return profile_type in ALLOWED_PROFILE_TYPES


def manifest_path_for_config(config_file: Path) -> Path:
    name = config_file.name
    suffix = ".filter-chain.conf"
    if name.endswith(suffix):
        return config_file.with_name(name[: -len(suffix)] + ".filter-chain.manifest.json")
    return config_file.with_suffix(".manifest.json")


def profile_id_for_config(config_file: Path) -> str:
    name = config_file.name
    suffix = ".filter-chain.conf"
    if name.endswith(suffix):
        return name[: -len(suffix)]
    return config_file.stem


def analyze_config_text(text: str) -> dict[str, object]:
    gains = [float(value) for value in _GAIN_RE.findall(text)]
    labels = _LABEL_RE.findall(text)
    preamp_match = _PREAMP_RE.search(text)
    source_match = _SOURCE_FILE_RE.search(text)

    return {
        "appears_generated_by_pipetune": "Generated by PipeTune Linux" in text
        or "PipeTune Linux generated PipeWire filter-chain configuration" in text,
        "filter_chain_config": "libpipewire-module-filter-chain" in text or "filter.graph" in text,
        "filter_count": len(labels),
        "filter_labels": labels,
        "preamp_db": float(preamp_match.group(1)) if preamp_match else None,
        "source_file": source_match.group(1).strip() if source_match else None,
        "max_positive_gain_db": max(gains) if gains else None,
        "max_negative_gain_db": min(gains) if gains else None,
        "suspicious_positive_gain": any(gain > 6.0 for gain in gains),
    }


def build_profile_metadata(config_file: Path, profile_name: str, profile_type: str, text: str) -> ProfileSafetyMetadata:
    analysis = analyze_config_text(text)
    warnings: list[str] = []
    notes = ["Generated manifest is local metadata only. It does not install or activate this profile."]

    if not bool(analysis["appears_generated_by_pipetune"]):
        warnings.append("Config does not clearly appear to be generated by PipeTune.")
    if analysis["preamp_db"] is None:
        warnings.append("Preamp metadata is missing.")
    if bool(analysis["suspicious_positive_gain"]):
        warnings.append("Suspicious positive gain above +6 dB detected.")

    requires_manual = profile_type in {"headphone", "laptop_speaker", "system", "unknown"}
    hardware_sensitive = profile_type in {"headphone", "laptop_speaker", "system"}

    return ProfileSafetyMetadata(
        profile_id=profile_id_for_config(config_file),
        profile_name=profile_name,
        profile_type=profile_type,
        target_device_name=profile_name,
        target_device_type=profile_type,
        generated_by="PipeTune Linux",
        generator_version=__version__,
        source_format="AutoEQ" if analysis["source_file"] else None,
        source_file=analysis["source_file"] if isinstance(analysis["source_file"], str) else None,
        created_at=datetime.now(timezone.utc).isoformat(timespec="seconds"),
        preamp_db=analysis["preamp_db"] if isinstance(analysis["preamp_db"], float) else None,
        max_positive_gain_db=analysis["max_positive_gain_db"] if isinstance(analysis["max_positive_gain_db"], float) else None,
        max_negative_gain_db=analysis["max_negative_gain_db"] if isinstance(analysis["max_negative_gain_db"], float) else None,
        filter_count=int(analysis["filter_count"]),
        enabled_filter_count=int(analysis["filter_count"]),
        requires_manual_output_confirmation=requires_manual,
        auto_apply_safe=False,
        hardware_quirk_sensitive=hardware_sensitive,
        notes=notes,
        warnings=warnings,
    )
