"""Profile safety check and activation preflight."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from pipetune.safety.manifest import load_manifest_for_config, manifest_path_for_config
from pipetune.safety.metadata import analyze_config_text
from pipetune.safety.models import ProfilePreflightResult, ProfileSafetyCheck
from pipetune.safety.quirk_status import collect_hardware_quirk_metadata
from pipetune.safety.readiness import decide_activation_readiness


def run_profile_safety_check(config_file: Path) -> ProfileSafetyCheck:
    warnings: list[str] = []
    errors: list[str] = []

    if not config_file.exists() or not config_file.is_file():
        return ProfileSafetyCheck(
            file_path=str(config_file),
            exists=False,
            readable=False,
            appears_generated_by_pipetune=None,
            filter_chain_config=None,
            filter_count=0,
            manifest_present=False,
            preamp_metadata="unknown",
            safety_status="fail",
            errors=[f"Config file not found: {config_file}"],
        )

    try:
        text = config_file.read_text(encoding="utf-8", errors="replace")
    except OSError as exc:
        return ProfileSafetyCheck(
            file_path=str(config_file),
            exists=True,
            readable=False,
            appears_generated_by_pipetune=None,
            filter_chain_config=None,
            filter_count=0,
            manifest_present=False,
            preamp_metadata="unknown",
            safety_status="fail",
            errors=[f"Config file could not be read: {exc}"],
        )

    analysis = analyze_config_text(text)
    manifest = load_manifest_for_config(config_file)
    manifest_present = manifest is not None
    profile_type = _profile_type_from_manifest(manifest)

    if not manifest_present:
        warnings.append("Manifest is missing.")
    if not bool(analysis["appears_generated_by_pipetune"]):
        warnings.append("Config does not clearly appear generated by PipeTune.")
    if not bool(analysis["filter_chain_config"]):
        errors.append("Config does not appear to be a PipeWire filter-chain config.")
    if analysis["preamp_db"] is None:
        warnings.append("Preamp metadata is missing.")
    if bool(analysis["suspicious_positive_gain"]):
        errors.append("Suspicious positive gain above +6 dB detected.")
    if profile_type == "laptop_speaker" and "limiter" not in text.lower() and "high-pass" not in text.lower():
        warnings.append("Laptop speaker profile has no high-pass or limiter marker.")

    status = "fail" if errors else ("warn" if warnings else "pass")
    return ProfileSafetyCheck(
        file_path=str(config_file),
        exists=True,
        readable=True,
        appears_generated_by_pipetune=bool(analysis["appears_generated_by_pipetune"]),
        filter_chain_config=bool(analysis["filter_chain_config"]),
        filter_count=int(analysis["filter_count"]),
        manifest_present=manifest_present,
        preamp_metadata="present" if analysis["preamp_db"] is not None else "missing",
        safety_status=status,
        warnings=warnings,
        errors=errors,
        profile_type=profile_type,
    )


def render_profile_safety_check(check: ProfileSafetyCheck) -> str:
    lines = [
        "PipeTune Profile Safety Check",
        "",
        f"File: {check.file_path}",
        f"Appears generated by PipeTune: {_optional_bool(check.appears_generated_by_pipetune)}",
        f"Filter-chain config: {_optional_bool(check.filter_chain_config)}",
        f"Filter count: {check.filter_count}",
        f"Manifest present: {'yes' if check.manifest_present else 'no'}",
        f"Preamp metadata: {check.preamp_metadata}",
        f"Safety status: {check.safety_status}",
    ]
    if check.warnings:
        lines.extend(["", "Warnings:"])
        lines.extend(f"* {warning}" for warning in check.warnings)
    if check.errors:
        lines.extend(["", "Errors:"])
        lines.extend(f"* {error}" for error in check.errors)
    lines.extend(["", "No system configuration was modified."])
    return "\n".join(lines)


def run_profile_preflight(config_file: Path) -> ProfilePreflightResult:
    safety_check = run_profile_safety_check(config_file)
    manifest = load_manifest_for_config(config_file)
    hardware = collect_hardware_quirk_metadata()

    profile = manifest.get("profile", {}) if isinstance(manifest, dict) else {}
    profile_name = str(profile.get("profile_name") or config_file.stem)
    profile_type = str(profile.get("profile_type") or safety_check.profile_type or "unknown")
    auto_apply_safe = bool(profile.get("auto_apply_safe", False))
    requires_manual = bool(profile.get("requires_manual_output_confirmation", False))

    readiness = decide_activation_readiness(
        safety_check=safety_check,
        manifest_present=manifest is not None,
        profile_type=profile_type,
        auto_apply_safe=auto_apply_safe,
        requires_manual_output_confirmation=requires_manual,
        hardware_quirk=hardware,
    )

    return ProfilePreflightResult(
        profile_name=profile_name,
        profile_type=profile_type,
        config_path=str(config_file),
        manifest_path=str(manifest_path_for_config(config_file)) if manifest is not None else None,
        manifest_present=manifest is not None,
        hardware_quirk=hardware,
        readiness=readiness,
    )


def render_profile_preflight(result: ProfilePreflightResult) -> str:
    lines = [
        "PipeTune Profile Activation Preflight",
        "",
        f"Profile: {result.profile_name}",
        f"Type: {result.profile_type}",
        f"Config: {result.config_path}",
        f"Manifest: {'found' if result.manifest_present else 'missing'}",
        "",
        "Hardware quirk status:",
        f"* detected: {'yes' if result.hardware_quirk.quirk_detected else 'no'}",
        f"* type: {result.hardware_quirk.quirk_type or 'unknown'}",
        f"* auto-switch safe: {'yes' if result.hardware_quirk.auto_switch_safe else 'no'}",
        f"* manual output confirmation required: {'yes' if result.hardware_quirk.requires_manual_output_confirmation else 'no'}",
        "",
        f"Activation readiness: {result.readiness.status}",
    ]
    if result.readiness.reasons:
        lines.extend(["", "Reasons:"])
        lines.extend(f"* {reason}" for reason in result.readiness.reasons)
    if result.readiness.warnings:
        lines.extend(["", "Warnings:"])
        lines.extend(f"* {warning}" for warning in result.readiness.warnings)
    if result.readiness.recommended_next_steps:
        lines.extend(["", "Recommended next steps:"])
        lines.extend(f"{index}. {step}" for index, step in enumerate(result.readiness.recommended_next_steps, start=1))
    lines.extend(["", "No system configuration was modified."])
    return "\n".join(lines)


def _profile_type_from_manifest(manifest: dict[str, Any] | None) -> str:
    if not isinstance(manifest, dict):
        return "unknown"
    profile = manifest.get("profile")
    if not isinstance(profile, dict):
        return "unknown"
    return str(profile.get("profile_type") or "unknown")


def _optional_bool(value: bool | None) -> str:
    if value is True:
        return "yes"
    if value is False:
        return "no"
    return "unknown"
